In [6]:
import pandas as pd

s=pd.Series([10,20,30])
print(s[0],"\n")
print(s[0:2])
print(s[:])

10

0    10
1    20
dtype: int64
0    10
1    20
2    30
dtype: int64

In [7]:
s=pd.Series([10,20,30], index=['a','b','c'])
print(s['a'],"\n")

10

In [16]:
df1=pd.DataFrame({
    "Name":["Pandu","Pappu","Pinky"],
    "Age":[25,49,30],
    "Score":[85,82,90]
})
df1

    Name  Age  Score
0  Pandu   25     85
1  Pappu   49     82
2  Pinky   30     90

In [74]:
df=pd.read_csv("titanic.csv")
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [14]:
df.sample(3)      # random sample

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
519,520,0,3,"Pavlovic, Mr. Stefo",male,32.0,0,0,349242,7.8958,NaN,S
610,611,0,3,"Andersson, Mrs. Anders Johan (Alfrida Konstant...",female,39.0,1,5,347082,31.2750,NaN,S
731,732,0,3,"Hassan, Mr. Houssein G N",male,11.0,0,0,2699,18.7875,NaN,C

In [15]:
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [17]:
df1["Age"]
df1[["Name", "Score"]]

    Name  Score
0  Pandu     85
1  Pappu     82
2  Pinky     90

In [33]:
print(df1.loc[0,"Name"])        # Access row by label/index
print(df1.loc[:])        # Access all rows

print(df1.iloc[0,0])       # Access row by integer location

Pandu
    Name  Age  Score
0  Pandu   25     85
1  Pappu   49     82
2  Pinky   30     90
Pandu

In [35]:
df1[df1["Score"] > 85]

    Name  Age  Score
2  Pinky   30     90

In [69]:
df["Age"].isnull().sum()  # titanic

np.int64(177)

In [39]:
df.shape

(891, 12)

In [75]:
df["Age"]=df["Age"].fillna(df["Age"].mean())     # fillna(x)    x=anythiing want to fill
df.shape

(891, 12)

In [79]:
df.groupby("Sex")["Fare"].mean()

Sex
female    44.479818
male      25.523893
Name: Fare, dtype: float64


### 1. Core Objects
Series — 1D labeled array

DataFrame — 2D table (rows + columns)

### 2. Loading Data

`pd.read_csv()` — load CSV

`pd.read_excel()`  — load Excel

`pd.read_json()`  — load JSON

### 3. Quick Inspection

`df.head()` — first rows

`df.tail()` — last rows

`df.shape` — (rows, cols)

`df.info()` — dtypes + nulls

`df.describe()` — stats summary

### 4. Column & Row Selection

`df["col"]` — single column

`df[["c1","c2"]]` — multiple columns

`df.iloc[i, j]` — integer position

`df.loc[row, col]` — label based

### 5. Filtering Rows

`df[df["col"] > value]`

Multiple conditions:  `df[(df["A"] > 5) & (df["B"] < 10)]`

### 6. Missing Values (VERY COMMON)

`df.isnull().sum()` — count nulls

`df.dropna()` — drop rows with null

`df.fillna(value)` — fill nulls

Used for:
    -Data cleaning

    -Preprocessing

### 7. Type Conversion

`df["col"].astype(int)`

`pd.to_datetime()`

### 8. Sorting

`df.sort_values("col")`

`df.sort_values("col", ascending=False)`

### 9. GroupBy (CORE FOR ANALYSIS)

`df.groupby("col").mean()`

`df.groupby("col")["target"].agg(["mean","count"])`

Used for:

-Aggregations

-Feature insights

### 10. Apply & Map

`df["col"].apply(func)`

`df["col"].map(dict)`

Used for:

-Feature engineering

-Transformations

### 11. Renaming & Dropping

`df.rename(columns={"old":"new"})`

`df.drop(columns=["col"])`

`df.drop(index=[0,1])`

### 12. Handling Duplicates

`df.duplicated()`

`df.drop_duplicates()`

### 13. Merging & Joining (REAL-WORLD)

`pd.merge(df1, df2, on="id")`

`df.join(df2)`

Used for:

-Combining datasets

### 14. Creating New Features

`df["new_col"] = df["A"] / df["B"]`

Core for ML feature engineering.

### 15. Categorical Data

`pd.get_dummies(df["cat"])`

astype("category")

Used for:

-Encoding features

### 16. Index Handling

`df.set_index("col")`

`df.reset_index()`

### 17. Exporting Data

`df.to_csv("file.csv", index=False)`

`df.to_excel("file.xlsx")`

### 18. Performance Tips

Avoid row-wise loops

Prefer vectorized ops

Use categorical dtype for large categorie